# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  venues = Venue.create([{name: "Precint Hotel", address:"60 Swan St", suburb: "Richmond", postcode: , description:"Originally established in 1926, the Precinct Hotel today represents the culinary, corporate and casual delights that see Melbourne as a stand out international destination for visitors and preferred abode for many. Nestled in the heart of Richmond and simultaneously catering for a versatile range of occasions, the Precinct Hotel is a family owned and operated establishment that offers a warm yet sophisticated atmosphere, guaranteed to make any soiree an unforgettable occasion. From intimate dining and live entertainment to big screen sporting events over the weekend... Precinct Hotel is the place to be in Melbourne" },
    {name:"Yah Yah's", address:"99 Smith St", suburb:"Fitzroy",postcode: , description: "Yah Yah's hosts bands and DJs every Thursday, Friday, Saturday and Sunday night. We spin rock, soul, garage, surf, exotica, 60s, 70s and more. "},
    {name: "The Sporting Globe", address:"690 Mt Alezander Rd", suburb:"Monee Ponds", postcode: ,description: "The Sporting Globe - Moonee Ponds is the latest edition to an award winning bar and grill group in Victoria, Australia. The concept is one where modern New York Sports Bar meets ‘true blue’ Aussie pub culture, with meals done to the highest quality. The menu features great steaks, burgers and wraps as well as international best sellers such as NY Buffalo Chicken Wings and signature sauces. A large range of beers are on tap, along with a strong selection of Australian wines and feature cocktails. The Sporting Globe has high community involvement in local sport, sponsoring many local teams and clubs. Its Sporting fit out make it the best place to watch sport in an unrivalled environment with over 40 screens and TAB facilities. "},
    {name:"The Gem", address: "289 Wellington St", suburb:"Collingwood", postcode: , description: "With great food and drink six nights a week, and some of Melbourne's best live music and DJs on the weekends, it's pretty easy to see why so many folks love to call The Gem in Collingwood their very own pub. Drop in sometime and see why the critics rate our pub grub as some of the best damn pub food in Melbourne. We were also the original southern cuisine pub in Melbourne – and don't forget our famous Sunday Texas BBQ!"},
    {name:"Revolver Upstairs", address:"229 Chapel St", suburb:"Prahran", postcode: , description:"Ultimately your enjoyment of Revolver depends on a number of variables - music, crowdedness, light levels - but if you can ignore the hype (positive and negative) and look for a venue that is relaxed and, in its own funny way, stylish, this is one institution that long ago earned its stripes and continues to come up with the goods." },
    {name:"Prince of Wales Bandroom", address:"29 Fitzroy St", suburb: "St Kilda", postcode: , description:"The cornerstone of St. Kilda's musical pleasures resides within The Prince of Wales Bandroom, near the corner of Fitzroy and Acland Streets. The Prince Bandroom has been a host to live music for more than 6 decades. Many of the best local and international bands and DJs play The Prince Bandroom when in Melbourne. A staple of the Melbourne live music scene for the last 100 years, this institution of Melbourne is the place to go to let your hair down and just have fun...! " },
    {name:"Katuk Bar", address:"517 Chapel St", suburb: "South Yarra", postcode: , description:"Katuk is difficult to describe. Yes, it's a Chapel Street bar, but it doesn't try too hard to be trendy. Yes, it's a little bit quirky, without needing to be totally off-the-wall. And yes, it's comfortable, but without sacrificing cleanliness, class, or style."},
    {name:"Maeve Fox Bar", address:"472 Church St", suburb:"Richmond", postcode: , description: "Consisting of 3 separate areas, the Main Bar is a convergence of old and refined with new forming an eclectic and elegant bar experience. Unique, lavish and decadent, this area is perfect for a quiet drink after work or a night out with friends. The Trophy lounge is a favourite to many at Maeve Fox. With a prominent design and theme this room becomes the perfect companion to any function. Head to the top level of Maeve Fox to the Glass Room, and you will be greeted with unobstructed views of the city skyline, the perfect environment for any occasion."},
    {name:"Laika Cocktail Lounge", address:"9 Fitzroy St", suburb:"St Kilda", postcode: , description: "Every nook and cranny is lavishly drenched in leather and plush fabrics; it's comfortable and sexy. The staff are casually elegant in their 1930's relaxed black tie and are efficiency personified, craving to help you through the impressive drinks list (some 300 bottles of champagne, wine and spirits). No matter what your drinking desire, Laika has something to cater for all tastes and preferences, providing customers with an elegant atmosphere in which to enjoy a night out in St Kilda. With 4 rooms, each with its own unique feel and ambience, newcomers to St Kilda looking to endulge their senses need not look much further then Laika Cocktail Lounge... simply superb. "},
    {name:"Khokalat Bar", address:"43 Hardware Lane", suburb:"Melbourne", postcode: , description: "The home of RnB in Melbourne"},
    {name:"John Curtin Hotel", address:"29 Lygon St", suburb:"Melbourne", postcode: , description: "A venue tailor made for live music enthusiasts, the John Curtin Hotel is a welcome addition to the saturated Melbourne live music scene. The 300 capacity bandroom has been designed to ensure an unrestricted view of the large stage from anywhere in the room. Complemented by a HK Audio PA system specifically in stalled to deliver the highest quality sound on stage and to the entire audience. Located at the city end of Lygon St Carlton, a short walk from Melbourne Central Station, The Curtin Bandroom is easily accessible by public transport. Rear access enables convenient load in/out with secure over night gear storage and private dressing room available. Licensed until 3am Monday - Saturday, The Curtin is surrounded by couches and is the ideal location to host private showcases/functions and after show parties."},
    {name:"Alumbra Lounge", address:"Shed 9, Central Pier, 161 Harbour Esplanade", suburb:"Docklands",postcode: , description: "Its the premiere venue in Melbourne's Dockland precinct with a host of weekly events. Whether it is old skool house and rnb or selective house music, Alumbra has played host to some of the most memorable nights in Melbourne nightlife history. The venue's elegant decor is counter balanced perfectly by the uplifting tunes spun by Alumbra's enviable list of resident DJ's, making a visit to Docklands incomplete without a brief stop over at Alumbra."},
    {name:"Club Dakota", address:"123-127 Maroondah Hwy", suburb:"Ringwood", postcode: ,description: "Brings the best DJ's and bands to Ringwood for your entertainment. The nightclub room comes alive on Friday and Saturday nights. The 2nd room provides a warm and relaxing side, playing cool tunes, but is also perfect for your next function. Friday nights play the latest and greatest RnB and Hip Hop beats, and Saturday nights are just... well... simply massive. One of the few venue's in Melbournes West that matches it with the best of the Nightclubs in Melbourne's CBD and Melbourne's South."},
    {name:"Billboard Nightclub", address:"170 Russell St", suburb:"Melbourne", postcode: ,description: "Billboard has been an entertainment venue for more than 40 years. Its name is synonymous with quality entertainment for two generations of Melburnians. The venue has evolved today into an upscale multi-purpose space the perfect location for concerts, theatre, university and charity balls, large corporate functions. We are a first choice venue for both international and 'A' grade domestic artists of every genre including full on classic rock, the bleeps and tweaks of indie/electro, in your face metal and the intensity of punk and grunge. In the middle of all that the venue has hosted some of the worlds best dance artists. "},
    {name:"Cherry Bar", address: "ACDC Ln", suburb: "Melbourne", postcode: , description: "Opening in 1999, tucked away down one of the CBD's intriguing little alleyways, Cherry is Melbourne's first authentic Rock bar, showcasing some of the greatest rock and soul music from the past half a century. Regular DJs spin everything from 50s style Northern Soul right through to modern contemporary Rock n' Roll, with a weekly timetable that is sure to have something for everyone. Cherry is one of Melbourne's more alluring bar experiences, leaving you wanting more cherry' baby yeah! With a wide variety of brews, New Zealand's Monteith's, England's Newcastle Brown Ale, to name but two, and a plethora of local & European drops, Cherry bar is the beer drinker's delight."}
  ])

  events = Event.create([{name: "Revolver Wednesday", date: "May 11 2016", time: "19.00" , artist: "DJ Danielsan" , gender: "Dance" },
    {name: "Watermelon Sundaes", date: "May 15 2016", time: "19.00",  gender: "Hip-hop" },
    {name: "Maddawg Mondays", date: "May 16 2016", time: "19.00" , gender: "old-rock" },
    {name: "Friends of friends", date: "May 27 2016", time: "22.00" , gender: "eletronic" },
    {name: "Bag Raiders", date: "May 29 2016", time: "20.00" , gender: "House" },
    {name: "Dance Technique", date: "May 12 2016", time: "" , gender: "dance-techno" },
    {name: "No money No Problems", date: "May 12 2016", time: "20.00" ,gender: "Hip-hop" },
    {name: "Razzmatazz Indie Discotheque
", date: "May 21 2016", time: "21.30" , gender: "indie" },

    ])
